name: "release"

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  APP_ROOT: ./app
  PROJECT_ID: test-project-373118
  PROJECT_NUMBER: 593997455442
  REGION: asia-northeast1
  WORKLOAD_IDENTITY_POOL: my-github-pool7
  WORKLOAD_IDENTITY_POOL_PROVIDER: my-github-pool-provider7
  REPOSITORY_NAME: my-repository
  IMAGE_NAME: sample-app

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WORKLOAD_IDENTITY_POOL }}/providers/${{ env.WORKLOAD_IDENTITY_POOL_PROVIDER }}

      - run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          file: ${{ env.APP_ROOT }}/Dockerfile
          context: ${{ env.APP_ROOT }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
